# Generated by Django 5.2.6 on 2026-01-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
